# This workflow will add gapps as docker container to Azure App Service and configure the container
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{ secrets.WEBAPP }} # set this to your application's name

jobs:
  configure:
    runs-on: ubuntu-latest

    environment:
      name: "gapps"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      # get the source files
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/gapps:latest
          build-args: |
            KC_DB_URL_HOST=${{ secrets.DB_HOST }}
            KC_DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            KC_DB_USERNAME=${{ secrets.DB_USER }}
            KC_DB_NAME=${{ secrets.DB_NAME }}

      # set the container image on azure webapp
      - name: Set Container on Azure WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PRODUCTION }}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/gapps:latest

      # login with an azure service principal
      # created with: az ad sp create-for-rbac --name gapps2 --role contributor --scopes /subscriptions/219ed260-8593-4c06-8304-49b26e912f63/resourceGroups/govradar-resource-group/providers/Microsoft.Web/sites/govradar-gapps --sdk-auth
      - uses: azure/login@v1
        with:
          creds: "${{ secrets.SERVICE_PRINCIPAL }}"

      # set the gapps environment variables, see 
      - name: Set Container Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
                {
                    "name": "DOCKER_REGISTRY_SERVER_URL",
                    "value": "${{ secrets.REGISTRY_LOGIN_SERVER }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                    "value": "${{ secrets.REGISTRY_USERNAME }}",
                    "slotSetting": false
                },
                {
                    "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                    "value": "${{ secrets.REGISTRY_PASSWORD }}",
                    "slotSetting": false
                },
                 {
                    "name": "POSTGRES_USER",
                    "value": "${{ secrets.POSTGRES_USER }}",
                    "slotSetting": false
                },
                 {
                    "name": "POSTGRES_HOST",
                    "value": "${{ secrets.POSTGRES_HOST }}",
                    "slotSetting": false
                },
                 {
                    "name": "POSTGRES_PASSWORD",
                    "value": "${{ secrets.POSTGRES_PASSWORD }}",
                    "slotSetting": false
                },
                 {
                    "name": "POSTGRES_DB",
                    "value": "${{ secrets.POSTGRES_DB }}",
                    "slotSetting": false
                },
                {
                  "name": "KC_PROXY",
                  "value": "edge",
                  "slotSetting": false
                },
                {
                  "name": "PROXY_ADDRESS_FORWARDING",
                  "value": "true",
                  "slotSetting": false
                }
            ]
